[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer_runs = 1_000_000
gas_reports = ["ERC20Eligibility", "ERC721Eligibility", "MultiERC1155Eligibility", "HypercertsEligibility"]
auto_detect_solc = false
solc = "0.8.19"
bytecode_hash = "none"
remappings = [
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/",
  "hats-protocol/=lib/hats-protocol/src/",
  "hats-module/=lib/hats-module/src/",
  "decentralist/=lib/decentralist/src/",
  "@openzeppelin-contracts/=lib/openzeppelin-contracts/",
  "solady/=lib/hats-module/lib/solady/src/"
]

[profile.ci]
fuzz = { runs = 5000 }
invariant = { runs = 1000 }

[profile.lite]
fuzz = { runs = 32 }
invariant = { runs = 10 }
# Speed up compilation and tests during development.
optimizer = false

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 2
wrap_comments = true

[rpc_endpoints]
local = "http://localhost:8545"
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
optimism = "https://optimism-mainnet.infura.io/v3/${INFURA_KEY}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_KEY}"

[etherscan]
mainnet = {key = "${ETHERSCAN_KEY}", url = "https://api.etherscan.io/api"}
optimism = {key = "${OPTIMISM_KEY}", url = "https://api-optimistic.etherscan.io/api"}
sepolia = {key = "${ETHERSCAN_KEY}", url = "https://api-sepolia.etherscan.io/api"}

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
